 #===========================================================================
# allowed DPIs
#===========================================================================
dpis:
  - 254
  - 190
  - 127

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000
  - 10000000
  - 20000000
  - 40000000
  - 100000000
  - 140000000
  
#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
 
  - !ipMatch
    host: 127.0.0.1
    # Allow to all hosts
    mask: 0.0.0.0
   
layouts:
  #===========================================================================
  A4 landscape:
  #===========================================================================
    mainPage:
      rotation: true
      landscape: true
      pageSize: A4
      backgroundPdf: '${configDir}/template.pdf'      
      header:
        height: 50
        items:
          - !text
            font: Helvetica
            fontSize: 30
            align: right
#            text: '${mapTitle}'
      items:
        - !map
          width: 480
          height: 480
          absoluteX:322
          absoluteY:545
        - !columns
          absoluteX: 142
          absoluteY: 80
          width: 160
          items:
            - !scalebar
              align: right
              maxSize: 160
              type: 'bar sub'
              intervals: 5
        - !columns
          absoluteX: 765
          absoluteY: 535
          width: 30
          items:
            - !image
              maxWidth: 30
              maxHeight: 30
              url: 'file://${configDir}/Arrow_North_CFCF.svg'
              rotation: '${rotation}'
        - !columns
          absoluteX: 50
          absoluteY: 450
          width: 255
          height:50
          items:
            - !text
                text: '${title}'
                fontSize: 20
        - !columns
          absoluteX: 50
          absoluteY: 390
          width: 255
          height:280
          items:
            - !text
                text: '${comment}'
                fontSize: 12
#        - !columns
#          absoluteX: 57
#          absoluteY: 70
#          width: 300
#          items:
#            - !text
#              text: '${now yyyy} GeoNetwork opensource'  
#              fontEncoding: Cp1252
#              fontSize: 10
      footer: &commonFooter
        height: 20
        items:
          - !columns
            config:
              cells:
                - paddingBottom: 3   
            items:
              - !text
                align: left
                text: 'Système d Information de Gestion des Risques au Sénégal, ${now dd.MM.yyyy}'
              - !text
                align: right
                text: 'Page ${pageNum}/${pageTot}'
              
    lastPage:
      rotation: true
      landscape: true
      pageSize: A4   
      header:
        height: 50
        items:
          - !text
            font: Helvetica-bold
            fontSize: 12
            align: right
            text: 'Legends'
      items:
        - !legends
          defaultScale: 0.33
          borders: true
          maxIconWidth: 0
          maxIconHeight: 0
          classIndentation: 0
          layerSpace: 5
          layerFontSize: 10
      footer: &commonFooter
        height: 20
        items:
          - !columns
            config:
              cells:
                - paddingBottom: 3   
            items:
              - !text
                align: left
                text: 'Système d Information de Gestion des Risques au Sénégal, ${now dd.MM.yyyy}'
              - !text
                align: right
                text: 'Page ${pageNum}/${pageTot}'
              
          
